### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by pataquets**
Add Dockerfile to enable image building.
By now, I use the official Golang image, default tag (minimalist 'alpine' lacks git). More info at https://hub.docker.com/_/golang/

Just installing via `go get`. Default option to `dvara` if none provided is `--help` to show usage. 

Build:

```
$ docker build -t dvara .
```

Example run (assuming an already running MongoDB container named `mongo`):

```
$ docker run --dit --name dvara -p 6000-6010:6000-6010 --link mongo dvara -addrs mongo:27017 -dvara.proxy-all
```

Optional improvement to come:
- Create an 'official', based on your repo, automated build at Docker Hub for the image: https://docs.docker.com/docker-hub/builds/ . Just requires a free Docker Hub account and a following a quick 'Create automated build' process.

### CODE REVIEW

**Comment by pataquets** [comment]
Fixing subject and description, accidental early form submit :)

**Comment by daaku** [comment]
Hey thanks for writing this up @pataquets! I think I'd rather not have this be in repo though because I don't want to support an official docker image.

**Comment by pataquets** [comment]
Thanks for the prompt response @daaku!
It is completely understandable not wanting to support a Docker Hub image. No problem with that.
However, having a valid Dockerfile in the repo also serves:
- Having a handy ready-to-use local build image.
- Enables others to just mirror this repo and have easily updatable images on Docker Hub.
- Perhaps serves as a base image to more advanced uses.
A basic Dockerfile is worth having without the need on a official Docker Hub image and the canonical place for it to live is here, IMHO.
It doesn't hurt having it ready here, does it? :)

**Comment by daaku** [comment]
If it's in the repo it's something we have decided to support. So far it hasn't been been requested and we wouldn't use it internally so it would atrophy over time.

**Comment by pataquets** [comment]
I see you point. Agreed.
Since, it's just a ```go get``` install, I've gone ahead and created my own image (using the same Dockerfile) and published it on Docker Hub at https://hub.docker.com/r/pataquets/dvara/.
It can be run by doing ```docker run --rm -it pataquets/dvara``` and it will print out the help by default.

To make it more robust, do you recommend any specific Go version? 1.5? 1.6? 1.(latest)? (https://hub.docker.com/_/golang/)

**Comment by daaku** [comment]
Latest version works great!

**Pull request closed without merging**
